# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Onenex_CodeTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Onenex_CodeTest

pod 'SVProgressHUD'

  target 'Onenex_CodeTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Onenex_CodeTestUITests' do
    # Pods for testing
  end

end
